FROM eclipse-temurin:17
LABEL authors="SUJAY KUMAR.G"
WORKDIR "/DockerPractice"
COPY target/DockerPractice-0.0.1-SNAPSHOT.jar /app/sprinboot-docker-demo
ENTRYPOINT ["java", "-jar", "springboot-docker-demo"]